server:
  port: 8001
  context-path: /
  tomcat: 
    uri-encoding: UTF-8

logging:
  level: 
    root: WARN
    org.springframework: DEBUG

spring: 
  application: 
    name: springbootwebapp
  datasource: 
    url: jdbc:mysql://localhost:3306/imking?useSSL=false&useUnicode=true&characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    dbcp2:
      max-idle: 20
      min-idle: 5
      initial-size: 10
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      max-wait-millis: 30000
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 180000
      min-evictable-idle-time-millis: 600000
  session: 
    store-type: redis
  redis: 
    database: 0
    host: localhost
    port: 6379
    password: 
    pool:
      max-active: 20
      max-wait: -1
      max-idle: 20
      min-idle: 0

mybatis:
  mapperLocations: classpath*:Mapper/**/*.xml
  configuration: 
    cache-enabled: false
    aggressive-lazy-loading: false
    use-generated-keys: false
    auto-mapping-behavior: partial
    default-executor-type: reuse
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    local-cache-scope: statement
    
    